name: 'public abstract Gravy : Power'
favicon: null
layout_spectrum: 0.66225
typography_spectrum: 0.69454
title: 'public abstract Gravy : Power'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27808464-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.0625
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
