name: 'public abstract Gravy : Power'
favicon: null
layout_spectrum: 0.63877
typography_spectrum: 0.69454
title: 'public abstract Gravy : Power'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27808464-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#964b24'
    - '#a06c51'
    - '#d4baa8'
    - '#eed3c8'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
