name: 'public abstract Gravy : Power'
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'public abstract Gravy : Power'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27808464-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#494d56'
    - '#850000'
    - '#b6b7bc'
    - '#d2fafe'
    - '#6ea296'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
