name: 'public abstract Gravy : Power'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25264
title: 'public abstract Gravy : Power'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27808464-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.04455825290642679
  lightness: 0.3233911271672696
  saturation: 0.1263302422594279
  rhythmicContrast: 0.4728528775740415
purpose: []
